### ISSUE TITLE
look into *not* using the root logger

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#75]
Installing vext.pyqt4 suppresses all logging for some as yet inexplicable reason. Need to track down the origin of this bug and eliminate it. The simplest solution may be to replace the custom logging with default Python logging. 

I will attempt to do some basic experimentation to figure out when/how this happens.

**Comment by o-smirnov** [comment]
But the custom logging is but a thin veneer on top of the default Python logger, so I doubt it's what introduces the problem...

**Comment by JSKenyon** [comment]
It is possible that the problem is with using vext. However, short of splitting out the Tigger front and back-ends, I am not sure how we would avoid it. I have only just begun debugging this so there is still hope. It could be as simple as a misdirected output.

**Comment by JSKenyon** [comment]
Aha! I have sort of figured it out. When using vext, its logger gets initialised first. That also means that it sets up the root logger. It sets the logging level of the root logger to WARNING, which of course suppresses all of CubiCal's logging. I can potentially fix this by checking whether or not the vext logger is present at runtime and then reconfigure the log level of the root logger. This does put some extra rubbish in front of the log:

```
INFO:solver:[0.1/0.4 0.5/0.9 0.5Gb] D0T0F1: 114 iters, conv 99.12%, stall 3.81%, g/fl 0.00%, d/fl 0.00%, chi2 34.9 -> 1.781e-08 (36.97), noise 0.0311 -> 7.05e-07
```

Will see what I can do to make it a little prettier, Unless this appearance is acceptable. Thoughts @o-smirnov ?

**Comment by JSKenyon** [comment]
Have found an easy solution that restores old behaviour - remove all handlers at runtime. This will let CubiCal create a new root logger with the correct setup.

**Comment by JSKenyon** [comment]
Closing this. Should be fixed in master.

**Comment by o-smirnov** [comment]
Hmmm, I wonder if we're using logging in the right way though. Perhaps the root of the problem (pardon the pun) is that the MyLogger module grabs the root logger, thus creating the potential for such conflict with other packages.

It would be more elegant to create our own sub-logger, remove all handlers from it, and base all other loggers of that. Assuming this works. I'll look into it...

**Comment by JSKenyon** [comment]
Ok @o-smirnov. Will leave it up to you. I have already merged the fix into master, but it is a necessary evil until we have a more elegant solution. No logging makes life difficult. If you do come up with something quick and easy, all you will need to do is remove the first few lines of code from main.py.

**Comment by o-smirnov** [comment]
Yep, I'm happy to leave your fix in place for now -- just keeping this open so we don't forget to do it right eventually.

**Comment by o-smirnov** [comment]
OK, I'm happy with the new scheme now. More compatible with the standard logging library. Two new options:
```
--log-verbose 0 
# or e.g. --log-verbose 0,data_handler=2
--log-file verbose 2,data_handler=4
```
The first one sets the console verbosity level. Only messages of level 0 or lower will be printed (e.g. the ``log(1)<<message`` invocations will be ignored), but specific modules can have their verbosity level upped for debugging.

The second one sets the logfile verbosity level. Default is same as console, but can be overridden to make the logfile e.g. more detailed.

Underneath, it will issue level-0 messages as ``logging.INFO``, level-1 messages as ``logging.INFO-1``, etc.

**Comment by o-smirnov** [comment]
Still a problem when vext  is installed, see discussion on #101. @JSKenyon, so I just need to run setup.py from the current master, to get vext installed, for this to rear its head?

**Comment by JSKenyon** [comment]
@o-smirnov Yes indeed. At least it was that simple for me. In a fresh venv, just to be safe.

**Comment by o-smirnov** [comment]
Well my current much-beloved venv is now broken with
```
$ gocubical 
...
pkg_resources.UnknownExtra: astro-tigger 1.3.5 has no such extra feature 'venv'
```
I have no idea what's going on here. Will start fresh.
